matrix:
 include:
  - os: linux
    language: python
    python: 2.7
  - os: linux
    dist: trusty
    language: python
    python: 3.3
  - os: linux
    dist: xenial
    language: python
    python: 3.4
  - os: linux
    dist: xenial
    language: python
    python: 3.5
  - os: linux
    language: python
    python: 3.6
  - os: linux
    dist: xenial # or later
    language: python
    python: 3.7
  - os: linux
    dist: xenial # or later
    language: python
    python: 3.8-dev
  - os: linux
    dist: trusty
    language: java
    jdk: openjdk7
  - os: linux
    dist: xenial
    language: java
    jdk: openjdk8
  - os: linux
    language: java
    jdk: openjdk9
  - os: linux
    language: java
    jdk: openjdk10
  - os: linux
    language: java
    jdk: openjdk11
  - os: linux
    language: java
    jdk: openjdk12
   # Force error for earlier detection of python 2.7 windows build problems
  - os: linux
    language: python
    python: 2.7
    env: CFLAGS="-Wdeclaration-after-statement -Werror=declaration-after-statement"
  - os: osx
    language: generic

script: ./setup.py test

